### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [NguyenAnhThi/ReactPrework#1]
Very good work! It is a very beautiful submission. I can tell you will be a great student, because you added many extra features to this. Wonderful!

Quick notes:
* dead code at https://github.com/NguyenAnhThi/ReactPrework/blob/master/src/App.js#L46
* https://github.com/NguyenAnhThi/ReactPrework/blob/master/src/App.js#L44 you don't need to wrap `[tweetObj]` in an array, actually. 
* https://github.com/NguyenAnhThi/ReactPrework/blob/master/src/App.js#L96 not sure why you add a space there with `{" "}`. 
* you can do this in css, or locally like you did on https://github.com/NguyenAnhThi/ReactPrework/blob/master/src/Tweet.jsx#L73. We'll talk about each way in class. :)

Good work! One of the best submissions. Congratulations, you will receive an accepted confirmation with more details on the class location! See you Tuesday.

**Comment by NguyenAnhThi** [comment]
Thank you so much for the comments and your feedback!

> dead code at https://github.com/NguyenAnhThi/ReactPrework/blob/master/src/App.js#L46

Oops! I have forgotten to remove this line of code.

> https://github.com/NguyenAnhThi/ReactPrework/blob/master/src/App.js#L96 not sure why you add a space there with {" "}.

It is because of Auto format code  feature in VS CODE. I did not intend to add a space there with {" "}.


I am very happy and really excited to be joining the course.
Hope to see you soon!
